title: Zvířetník
baseURL: https://blissful-kirch-bd9e96.netlify.com/
languageCode: cs-cz
publishDir: public

menu:
  main:
    - name: Homepage
      url: /
      weight: 10
    - name: Archive
      identifier: post
      url: /post/
      weight: 20

params:
  description: Ochrana zvířat.
  authors: Kristýna Světnicová
  Denisa Hulánková
  Eva Neureiterová

